### ISSUE TITLE
Redstone orb is bugged

### ISSUE THREAD

**Issue by Frontrider** [Emasher/EmashersMods#129]
When i use the redstone wand, the orb allows me to see throught the ground. The orb is not transparent, but a solid block.

**Comment by Emasher** [comment]
I can't reproduce this in 1.2.0.4.

Are you using a texture or shader pack? What type of graphics controller are you using?

**Comment by Frontrider** [comment]
There was fastcraft installed. No texture or shader. AMD 4600 series.

**Comment by Emasher** [comment]
I still cannot reproduce this with the latest version of FastCraft (1.21) installed.

**Comment by Frontrider** [comment]
http://imgur.com/4hrT7w9

**Comment by Emasher** [comment]
Can you list the graphics settings you're using, including any you've configured using external utilities, as well as any mods that modify the graphics?

**Comment by Frontrider** [comment]
I have not configured graphics with external software, with the exeption of the render distance what i needed to lower it to load up maps.

The modlist.
http://pastebin.com/5LK9bfUn

**Comment by Emasher** [comment]
Does this still occur without any other mods installed?

**Comment by Frontrider** [comment]
Turning smooth lightning off triggers the bug.

**Comment by Emasher** [comment]
I've tried nearly every rendering related hook in the Block class and I can't seem to get it to work unless I make it extend BlockBreakable instead of BlockContainer (which is required to support the tile entity).

In the end, I decided to just make it render as a full size block when smooth lighting is turned off, as well as render the inside as well so you can't use it as an x-ray by going inside it.
